### ISSUE TITLE
torchattacks dont include ADAM method

### ISSUE THREAD

**Issue by tjuxiaoli** [lwmming/Cross-Modal-Attack#1]
When I was debugging main_ucf.py, I encountered an error in the attack model part, which showed that torchattacks doesn't have methods like ADAM_TAP11. I searched online for the included attack methods and couldn't find ADAM. Can anyone confirm if it's implemented?
the related code is：
ADAMTAP10 = torchattacks.ADAM_TAP(model_vgg16, eps=16.0/255, alpha=0.005, steps=60, momentum=1.0) # baseline
ADAMTAP10 = torchattacks.ADAM_TAP11(model_res101, eps=16.0/255, alpha=0.005, steps=60, momentum=1.0) # ours

**Comment by lwmming** [comment]
Thank you so much for your attention~ This issue has been fixed now. Thank you for checking the related codes.

**Comment by tjuxiaoli** [comment]
You're welcome! I'm glad to hear that the issue has been resolved
